"""no2

Revision ID: 391082729348
Revises: 83cffebb3f7d
Create Date: 2025-09-14 01:00:50.993924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391082729348'
down_revision = '83cffebb3f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
