"""model_file2

Revision ID: 56657f666fc8
Revises: 6029fb8e1bc2
Create Date: 2025-09-13 17:50:47.637577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56657f666fc8'
down_revision: Union[str, Sequence[str], None] = '6029fb8e1bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'age')
    # ### end Alembic commands ###
